const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const base = __dirname + '/..';
const code = fs.readFileSync(base + '/expertDecisionController.js', 'utf8');
const policy = fs.readFileSync(base + '/expertDecision/policy.js', 'utf8');
const policyContext = vm.createContext({});
vm.runInContext(policy.replace(/^export\s*\{[^}]*\};?/gm, '') + '\nthis.mergePolicy=mergePolicy;', policyContext);
assert.equal(policyContext.mergePolicy().expertLateP1RushMinimumLaunchArmy, 52);
const attack = fs.readFileSync(base + '/attackPlan.js', 'utf8');
const towerStart = attack.indexOf('AttackPlan.prototype.expertExposedTower = ');
const towerEnd = attack.indexOf('\n// IT14.45 ram assault state', towerStart);
assert(towerStart > 0 && towerEnd > towerStart);
const towerCtx = vm.createContext({difficulty:{EXPERT:5}, SquareVectorDistance:(a,b)=>(a[0]-b[0])**2+(a[1]-b[1])**2});
vm.runInContext('const AttackPlan=function(){};\n' + attack.slice(towerStart,towerEnd) + '\nthis.select=AttackPlan.prototype.expertExposedTower;',towerCtx);
const tower=(id,x)=>({id:()=>id,position:()=>[x,0],hasClass:k=>k==='Tower'});
const enemy=x=>({position:()=>[x,0],attackTypes:()=>['Melee']});
const group={Config:{difficulty:5},unitCollection:{length:52},position:[0,0]};
const buildings=new Map([[1,tower(1,-60)],[2,tower(2,60)]]);
assert.equal(towerCtx.select.call(group,{},new Map(),buildings,false).id(),1,'attack nearest undefended tower');
assert.equal(towerCtx.select.call(group,{},new Map(),buildings,true),undefined,'CC execution overrides tower');
assert.equal(towerCtx.select.call({...group,unitCollection:{length:20}}, {},new Map(),buildings,false),undefined,'thin army stays safe');
assert.equal(towerCtx.select.call(group,{},new Map(Array.from({length:15},(_,i)=>[i,enemy(-60)])),buildings,false).id(),2,'defended first tower is not exposed');
const start = code.indexOf('\n\tupdateExpertCombatAuthority(gameState)');
const end = code.indexOf('\n\tvisibleEnemyCombatCount(', start);
assert(start>0&&end>start);
const ctx=vm.createContext({PlayerID:2,EXPERT_DEFENSE:'defense',AttackPlan:{TYPE_DEFAULT:'Attack'},entityPosition:e=>e.position(),hasClass:(e,k)=>e.hasClass(k),isExpertBuildingSiegeEntity:()=>false,aiWarn:()=>{}});
vm.runInContext(code.slice(start,end).replace('updateExpertCombatAuthority(gameState)','function update(gameState)')+'\nthis.update=update;',ctx);
const plan={expertAuthorityOwned:true,targetPlayer:1,name:0,unitCollection:{length:2}};
const units=Array.from({length:94},(_,i)=>({id:()=>i+1,position:()=>[1,1],hasClass:k=>k==='CitizenSoldier',getMetadata:(_p,k)=>k==='plan'?-1:undefined}));
let attached=0;
const owner={isExpertControlActive:()=>true,HQ:{attackManager:{}},expertAdoptExistingCombatPlans:()=>{},expertEnsureCombatPlan:()=>{},expertCombatPlans:started=>started===true?[plan]:[],finishingState:()=>({active:true,targetPlayer:1,enemyPopulation:1}),expertAttachEntityToPlan:()=>{attached++;plan.unitCollection.length++;return true;},expertActivatePreownedMilitary:()=>{}};
ctx.update.call(owner,{getOwnUnits:()=>new Map(units.map(u=>[u.id(),u]))});
assert.equal(attached,78,'coherent finishing reinforcement uses idle military reserves');
assert.equal(plan.unitCollection.length,80);
const constructStart=code.indexOf('\n\tassignIdleConstruction(');
const constructEnd=code.indexOf('\n\tenforceNoIdleEconomyWorkers(',constructStart);
assert(constructStart>0&&constructEnd>constructStart);
const constructContext=vm.createContext({PlayerID:2,entityPosition:e=>e.position(),getLandAccess:()=>2,SquareVectorDistance:(a,b)=>(a[0]-b[0])**2+(a[1]-b[1])**2,hasLiveRepairOrder:()=>false,ensureRepairOrder:()=>({status:'ISSUED'}),Worker:{SUBROLE_BUILDER:'builder'},aiWarn:()=>{}});
vm.runInContext(code.slice(constructStart,constructEnd).replace('assignIdleConstruction(gameState, ent, accessIndex)','function construct(gameState, ent, accessIndex)')+'\nthis.construct=construct;',constructContext);
let built=0;const foundation={id:()=>5,position:()=>[12,0]};
const builder={position:()=>[0,0],id:()=>7,repair:()=>{built++},setMetadata:()=>{}};
assert(constructContext.construct.call({foundationsByClass:(_s,k)=>k==='Barracks'?[foundation]:[],HQ:{territoryMap:{getOwner:()=>2}}},{getOwnUnits:()=>new Map()},builder,2));
assert.equal(built,0,'order-verifier fixture reports issued without invoking engine repair');
console.log('PASS: 52-unit rush floor, tower suppression, coherent finishing reserve, and construction fallback.');
const ecoStart=code.indexOf('\n\tresearchExpertSurplusEcoParallel(');
const ecoEnd=code.indexOf('\n\tresearchExpertP1EcoSweep(',ecoStart);
assert(ecoStart>0&&ecoEnd>ecoStart);
let queued;
const ecoContext=vm.createContext({ResearchPlan:function(_state,name){this.type=name;},aiWarn:()=>{}});
vm.runInContext(code.slice(ecoStart,ecoEnd).replace('researchExpertSurplusEcoParallel(gameState, queues)','function research(gameState, queues)')+'\nthis.research=research;',ecoContext);
const queues={}, tech=['gather_mining_serfs',{_template:{modifications:[{value:'ResourceGatherer/Rates/stone.rock'}],cost:{food:100,wood:50,stone:0,metal:100}}}];
const state={currentPhase:()=>2,ai:{queueManager:{addQueue:name=>{queues[name] ||= {plans:[],hasQueuedUnits:()=>queues[name].plans.length>0,addPlan:p=>{queued=p;queues[name].plans.push(p);}}}}},getResources:()=>({food:1500,wood:800,stone:500,metal:450}),findAvailableTech:()=>[tech],isResearched:()=>false,isResearching:()=>false};
const ecoOwner={economyWorkerMetrics:()=>({stone:4,metal:2})};
assert(ecoContext.research.call(ecoOwner,state,queues));
assert.equal(queued.type,'gather_mining_serfs');
assert.equal(ecoContext.research.call(ecoOwner,state,queues),false,'do not queue duplicate while researching');
console.log('PASS: parallel surplus research consumes a safe bank without duplicate orders.');
